-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 13:05:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ADMINISTRADOR` (
  `ID_ADMINISTRADOR` INT NOT NULL,
  `NOMBRE_ADMINISTRADOR` VARCHAR(45) NULL,
  `APELLIDOS_ADMINISTRADOR` VARCHAR(45) NULL,
  `CORREO_ADMINSITRADOR` VARCHAR(45) NULL,
  `CONTRASENA_ADMINISTRADOR` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ADMINISTRADOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AREA` (
  `ID_AREA` INT NOT NULL,
  `NOMBRE_AREA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_AREA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPLEADO` (
  `ID_EMPLEADO` INT NOT NULL,
  `FK_ID_AREA` INT NOT NULL,
  `NOMBRE_EMPLEADO` VARCHAR(45) NULL,
  `APELLIDOS_EMPLEADO` VARCHAR(45) NULL,
  `CORREO_EMPLEADO` VARCHAR(45) NULL,
  `DIRECCION_EMPLEADO` VARCHAR(45) NULL,
  `TELEFONO_EMPLEADO` VARCHAR(45) NULL,
  INDEX `fk_EMPLEADO_AREA_idx` (`FK_ID_AREA` ASC) ,
  PRIMARY KEY (`ID_EMPLEADO`),
  CONSTRAINT `fk_EMPLEADO_AREA`
    FOREIGN KEY (`FK_ID_AREA`)
    REFERENCES `AREA` (`ID_AREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ADMINISTRADOR`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ADMINISTRADOR` (`ID_ADMINISTRADOR`, `NOMBRE_ADMINISTRADOR`, `APELLIDOS_ADMINISTRADOR`, `CORREO_ADMINSITRADOR`, `CONTRASENA_ADMINISTRADOR`) VALUES (1, 'Carlos Arturo', 'Cruz Ortega', 'ccruzortega@gmail.com', 'Arthur123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `AREA`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `AREA` (`ID_AREA`, `NOMBRE_AREA`) VALUES (1, 'Gerencia');
INSERT INTO `AREA` (`ID_AREA`, `NOMBRE_AREA`) VALUES (2, 'Talento Humano');
INSERT INTO `AREA` (`ID_AREA`, `NOMBRE_AREA`) VALUES (3, 'Tecnología');
INSERT INTO `AREA` (`ID_AREA`, `NOMBRE_AREA`) VALUES (4, 'Administrativa');
INSERT INTO `AREA` (`ID_AREA`, `NOMBRE_AREA`) VALUES (5, 'Innovación');

COMMIT;

