//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public int ID_ADMINISTRADOR { get; set; }
        public string NOMBRE_ADMINISTRADOR { get; set; }
        public string APELLIDOS_ADMINISTRADOR { get; set; }
        public string CORREO_ADMINSITRADOR { get; set; }
        public string CONTRASENA_ADMINISTRADOR { get; set; }
    }
}
