//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int ID_EMPLEADO { get; set; }
        public int FK_ID_AREA { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public string APELLIDOS_EMPLEADO { get; set; }
        public string CORREO_EMPLEADO { get; set; }
        public string DIRECCION_EMPLEADO { get; set; }
        public string TELEFONO_EMPLEADO { get; set; }

        public virtual area area { get; set; }
    }
}
